STR_ENGLISH  (IDS_DISPLAY_GROUP, "GROUP")
STR_SCHINESE (IDS_DISPLAY_GROUP, "分组")

STR_ENGLISH  (IDS_DISPLAY_KEY, "KEY")
STR_SCHINESE (IDS_DISPLAY_KEY, "曲调")

STR_ENGLISH  (IDS_DISPLAY_OCTSHIFT, "OCTAVE")
STR_SCHINESE (IDS_DISPLAY_OCTSHIFT, "八度音高")

STR_ENGLISH  (IDS_DISPLAY_PLAY, "PLAY")
STR_SCHINESE (IDS_DISPLAY_PLAY, "播放")

STR_ENGLISH  (IDS_DISPLAY_REC, "REC")
STR_SCHINESE (IDS_DISPLAY_REC, "录音")

STR_ENGLISH  (IDS_DISPLAY_SUSTAIN, "SUSTAIN")
STR_SCHINESE (IDS_DISPLAY_SUSTAIN, "延音踏板")

STR_ENGLISH  (IDS_DISPLAY_VELOCITY, "VELOCITY")
STR_SCHINESE (IDS_DISPLAY_VELOCITY, "键盘力度")

STR_ENGLISH  (IDS_ERR_INIT_DISPLAY, "Failed to initialize display. (%s, err=%d)")
STR_SCHINESE (IDS_ERR_INIT_DISPLAY, "初始化显示失败，请检查您的显卡支持3D加速，并且正确的安装了显卡驱动程序。（%s, hr=%d）")

STR_ENGLISH  (IDS_ERR_INIT_FONT, "Failed to initialize font. (%s)")
STR_SCHINESE (IDS_ERR_INIT_FONT, "初始化字体失败(%s)")

STR_ENGLISH  (IDS_ERR_LOAD_KEYMAP, "Unable to load key map, error code : %d.")
STR_SCHINESE (IDS_ERR_LOAD_KEYMAP, "无法载入按键映射， 错误码：%d")

STR_ENGLISH  (IDS_ERR_LOAD_MIDI, "Failed to open MIDI device.")
STR_SCHINESE (IDS_ERR_LOAD_MIDI, "打开MIDI设备失败")

STR_ENGLISH  (IDS_ERR_LOAD_VST, "Unable to load VST plugin, error code : %d.")
STR_SCHINESE (IDS_ERR_LOAD_VST, "无法载入VST插件， 错误码：%d")

STR_ENGLISH  (IDS_ERR_OPEN_SONG, "Failed to open song.")
STR_SCHINESE (IDS_ERR_OPEN_SONG, "打开乐谱失败！")

STR_ENGLISH  (IDS_ERR_OPEN_SONG_FORMAT, "Error open file, unsupported file format.")
STR_SCHINESE (IDS_ERR_OPEN_SONG_FORMAT, "无法打开文件, 不支持的文件格式！")

STR_ENGLISH  (IDS_ERR_OPEN_SONG_VERSION, "File is created by a newer version of FreePiano, please update to the latest version.")
STR_SCHINESE (IDS_ERR_OPEN_SONG_VERSION, "无法打开使用新版本创作的FreePiano音乐, 请升级至最新版本！")

STR_ENGLISH  (IDS_ERR_SAVE_SONG, "Failed to save song.")
STR_SCHINESE (IDS_ERR_SAVE_SONG, "保存乐谱失败！")

STR_ENGLISH  (IDS_FILTER_MAP, "Keymap (*.map)\0*.map\0")
STR_SCHINESE (IDS_FILTER_MAP, "键盘配置 (*.map)\0*.map\0")

STR_ENGLISH  (IDS_MENU_CONFIG, "Config")
STR_SCHINESE (IDS_MENU_CONFIG, "设置")

STR_ENGLISH  (IDS_MENU_CONFIG_OPTIONS, "Options...")
STR_SCHINESE (IDS_MENU_CONFIG_OPTIONS, "选项...")

STR_ENGLISH  (IDS_MENU_CONFIG_PLAYSPEED, "Play speed")
STR_SCHINESE (IDS_MENU_CONFIG_PLAYSPEED, "播放速度")

STR_ENGLISH  (IDS_MENU_FILE, "File")
STR_SCHINESE (IDS_MENU_FILE, "录音")

STR_ENGLISH  (IDS_MENU_FILE_EXPORT, "Export")
STR_SCHINESE (IDS_MENU_FILE_EXPORT, "导出")

STR_ENGLISH  (IDS_MENU_FILE_EXPORT_MP4, "Video File (MP4) ...")
STR_SCHINESE (IDS_MENU_FILE_EXPORT_MP4, "视频文件（MP4）...")

STR_ENGLISH  (IDS_MENU_FILE_EXPORT_WAV, "Wave file (WAV) ...")
STR_SCHINESE (IDS_MENU_FILE_EXPORT_WAV, "无损音频（WAV）...")

STR_ENGLISH  (IDS_MENU_FILE_INFO, "Information")
STR_SCHINESE (IDS_MENU_FILE_INFO, "歌曲信息")

STR_ENGLISH  (IDS_MENU_FILE_OPEN, "Open...")
STR_SCHINESE (IDS_MENU_FILE_OPEN, "打开...")

STR_ENGLISH  (IDS_MENU_FILE_PLAY, "Play")
STR_SCHINESE (IDS_MENU_FILE_PLAY, "播放")

STR_ENGLISH  (IDS_MENU_FILE_RECORD, "Record")
STR_SCHINESE (IDS_MENU_FILE_RECORD, "录制")

STR_ENGLISH  (IDS_MENU_FILE_SAVE, "Save...")
STR_SCHINESE (IDS_MENU_FILE_SAVE, "保存...")

STR_ENGLISH  (IDS_MENU_FILE_STOP, "Stop")
STR_SCHINESE (IDS_MENU_FILE_STOP, "停止")

STR_ENGLISH  (IDS_MENU_HELP, "Help")
STR_SCHINESE (IDS_MENU_HELP, "帮助")

STR_ENGLISH  (IDS_MENU_HELP_ABOUT, "About FreePiano...")
STR_SCHINESE (IDS_MENU_HELP_ABOUT, "关于 FreePiano...")

STR_ENGLISH  (IDS_MENU_HELP_HOMEPAGE, "Homepage")
STR_SCHINESE (IDS_MENU_HELP_HOMEPAGE, "软件主页")

STR_ENGLISH  (IDS_MENU_HELP_ONLINE, "Online Manual...")
STR_SCHINESE (IDS_MENU_HELP_ONLINE, "在线帮助...")

STR_ENGLISH  (IDS_MENU_INSTRUMENT, "Instrument")
STR_SCHINESE (IDS_MENU_INSTRUMENT, "音源")

STR_ENGLISH  (IDS_MENU_INSTRUMENT_BROWSE, "Browse...")
STR_SCHINESE (IDS_MENU_INSTRUMENT_BROWSE, "浏览...")

STR_ENGLISH  (IDS_MENU_INSTRUMENT_GUI, "Show VST instrument window")
STR_SCHINESE (IDS_MENU_INSTRUMENT_GUI, "显示VSTi音源界面")

STR_ENGLISH  (IDS_MENU_INSTRUMENT_SHOW_MIDI, "Show MIDI devices")
STR_SCHINESE (IDS_MENU_INSTRUMENT_SHOW_MIDI, "显示MIDI设备")

STR_ENGLISH  (IDS_MENU_INSTRUMENT_SHOW_VSTI, "Show VST instruments")
STR_SCHINESE (IDS_MENU_INSTRUMENT_SHOW_VSTI, "显示VSTi设备")

STR_ENGLISH  (IDS_MENU_KEYGROUP, "Keygroup")
STR_SCHINESE (IDS_MENU_KEYGROUP, "键盘分组")

STR_ENGLISH  (IDS_MENU_KEYMAP, "Keymap")
STR_SCHINESE (IDS_MENU_KEYMAP, "键盘布局")

STR_ENGLISH  (IDS_MENU_KEYMAP_LOAD, "Load...")
STR_SCHINESE (IDS_MENU_KEYMAP_LOAD, "载入...")

STR_ENGLISH  (IDS_MENU_KEYMAP_SAVE, "Save")
STR_SCHINESE (IDS_MENU_KEYMAP_SAVE, "保存")

STR_ENGLISH  (IDS_MENU_KEYMAP_SAVEAS, "Save As...")
STR_SCHINESE (IDS_MENU_KEYMAP_SAVEAS, "另存为...")

STR_ENGLISH  (IDS_MENU_KEY_CLEAR, "Clear")
STR_SCHINESE (IDS_MENU_KEY_CLEAR, "清除")

STR_ENGLISH  (IDS_MENU_KEY_CONTROL, "Control")
STR_SCHINESE (IDS_MENU_KEY_CONTROL, "控制器")

STR_ENGLISH  (IDS_MENU_KEY_NOTE, "Note")
STR_SCHINESE (IDS_MENU_KEY_NOTE, "音高")

STR_ENGLISH  (IDS_MENU_KEY_NOTESHIFT, "Note shift")
STR_SCHINESE (IDS_MENU_KEY_NOTESHIFT, "八度音高")

STR_ENGLISH  (IDS_MENU_KEY_SETTINGS, "Keymap settings...")
STR_SCHINESE (IDS_MENU_KEY_SETTINGS, "布局设置...")

STR_ENGLISH  (IDS_MENU_LANGUAGE, "Language")
STR_SCHINESE (IDS_MENU_LANGUAGE, "语言")

STR_ENGLISH  (IDS_MENU_LANGUAGE_CHINESE, "简体中文")
STR_SCHINESE (IDS_MENU_LANGUAGE_CHINESE, "简体中文")

STR_ENGLISH  (IDS_MENU_LANGUAGE_ENGLISH, "English")
STR_SCHINESE (IDS_MENU_LANGUAGE_ENGLISH, "English")

STR_ENGLISH  (IDS_MENU_SETTING_GROUP_ADD, "Add group")
STR_SCHINESE (IDS_MENU_SETTING_GROUP_ADD, "增加分组")

STR_ENGLISH  (IDS_MENU_SETTING_GROUP_CHANGE, "Change Group")
STR_SCHINESE (IDS_MENU_SETTING_GROUP_CHANGE, "切换分组")

STR_ENGLISH  (IDS_MENU_SETTING_GROUP_CLEAR, "Clear settings")
STR_SCHINESE (IDS_MENU_SETTING_GROUP_CLEAR, "清除配置")

STR_ENGLISH  (IDS_MENU_SETTING_GROUP_COPY, "Copy settings")
STR_SCHINESE (IDS_MENU_SETTING_GROUP_COPY, "拷贝配置")

STR_ENGLISH  (IDS_MENU_SETTING_GROUP_DEFAULT, "Restore default")
STR_SCHINESE (IDS_MENU_SETTING_GROUP_DEFAULT, "恢复默认配置")

STR_ENGLISH  (IDS_MENU_SETTING_GROUP_DEL, "Delete group")
STR_SCHINESE (IDS_MENU_SETTING_GROUP_DEL, "删除分组")

STR_ENGLISH  (IDS_MENU_SETTING_GROUP_INSERT, "Insert group")
STR_SCHINESE (IDS_MENU_SETTING_GROUP_INSERT, "插入分组")

STR_ENGLISH  (IDS_MENU_SETTING_GROUP_PASTE, "Paste settings")
STR_SCHINESE (IDS_MENU_SETTING_GROUP_PASTE, "粘贴配置")

STR_ENGLISH  (IDS_MIDI_INPUT_LIST_DEVICE, "Device")
STR_SCHINESE (IDS_MIDI_INPUT_LIST_DEVICE, "设备")

STR_ENGLISH  (IDS_MIDI_INPUT_LIST_DISABLED, "No")
STR_SCHINESE (IDS_MIDI_INPUT_LIST_DISABLED, "否")

STR_ENGLISH  (IDS_MIDI_INPUT_LIST_ENABLE, "Enable")
STR_SCHINESE (IDS_MIDI_INPUT_LIST_ENABLE, "启用")

STR_ENGLISH  (IDS_MIDI_INPUT_LIST_ENABLED, "Yes")
STR_SCHINESE (IDS_MIDI_INPUT_LIST_ENABLED, "是")

STR_ENGLISH  (IDS_MIDI_INPUT_LIST_REMAP, "Remap")
STR_SCHINESE (IDS_MIDI_INPUT_LIST_REMAP, "映射")

STR_ENGLISH  (IDS_MIDI_INPUT_LIST_REMAP_OUTPUT, "Output")
STR_SCHINESE (IDS_MIDI_INPUT_LIST_REMAP_OUTPUT, "输出")

STR_ENGLISH  (IDS_MIDI_INPUT_LIST_REMAP_INPUT, "In %d")
STR_SCHINESE (IDS_MIDI_INPUT_LIST_REMAP_INPUT, "输入 %d")

STR_ENGLISH  (IDS_OPEN_FILTER_SONG, "All songs (*.fpm, *.lyt)\0*.fpm;*.lyt\0")
STR_SCHINESE (IDS_OPEN_FILTER_SONG, "所有乐谱 (*.fpm, *.lyt)\0*.fpm;*.lyt\0")

STR_ENGLISH  (IDS_OPEN_FILTER_VST, "VST plugins (*.dll)\0*.dll\0")
STR_SCHINESE (IDS_OPEN_FILTER_VST, "VST 插件 (*.dll)\0*.dll\0")

STR_ENGLISH  (IDS_SAVE_FILTER_MP4, "Video files (*.mp4)\0*.mp4\0")
STR_SCHINESE (IDS_SAVE_FILTER_MP4, "视频文件 (*.mp4)\0*.mp4\0")

STR_ENGLISH  (IDS_SAVE_FILTER_SONG, "FreePiano song (*.fpm)\0*.fpm\0")
STR_SCHINESE (IDS_SAVE_FILTER_SONG, "FreePiano乐谱 (*.fpm)\0*.fpm\0")

STR_ENGLISH  (IDS_SAVE_FILTER_WAV, "Wave files (*.wav)\0*.wav\0")
STR_SCHINESE (IDS_SAVE_FILTER_WAV, "音频文件 (*.wav)\0*.wav\0")

// Settings dialogs
STR_ENGLISH  (IDS_SETTING_CAPTION, "Settings")
STR_SCHINESE (IDS_SETTING_CAPTION, "设置")

// play setting page
STR_ENGLISH  (IDS_SETTING_LIST_PLAY, "Channels")
STR_SCHINESE (IDS_SETTING_LIST_PLAY, "通道")

STR_ENGLISH  (IDS_SETTING_PLAY_INPUT, "In %d")
STR_SCHINESE (IDS_SETTING_PLAY_INPUT, "输入 %d")

STR_ENGLISH  (IDS_SETTING_PLAY_OUTPUT, "Out %d")
STR_SCHINESE (IDS_SETTING_PLAY_OUTPUT, "输出 %d")

STR_ENGLISH  (IDS_SETTING_PLAY_VELOCITY, "Velocity:")
STR_SCHINESE (IDS_SETTING_PLAY_VELOCITY, "力度：")

STR_ENGLISH  (IDS_SETTING_PLAY_TRANSPOSE, "Transpose:")
STR_SCHINESE (IDS_SETTING_PLAY_TRANSPOSE, "移调：")

STR_ENGLISH  (IDS_SETTING_PLAY_FOLLOW_KEY, "Follow key:")
STR_SCHINESE (IDS_SETTING_PLAY_FOLLOW_KEY, "跟随曲调：")

STR_ENGLISH  (IDS_SETTING_PLAY_OCTAVE, "Octave:")
STR_SCHINESE (IDS_SETTING_PLAY_OCTAVE, "八度：")

STR_ENGLISH  (IDS_SETTING_PLAY_CHANNEL, "Channel:")
STR_SCHINESE (IDS_SETTING_PLAY_CHANNEL, "输出通道：")

STR_ENGLISH  (IDS_SETTING_PLAY_BANK, "Bank:")
STR_SCHINESE (IDS_SETTING_PLAY_BANK, "音色组：")

STR_ENGLISH  (IDS_SETTING_PLAY_PROGRAM, "Program:")
STR_SCHINESE (IDS_SETTING_PLAY_PROGRAM, "音色：")

STR_ENGLISH  (IDS_SETTING_PLAY_SUSTAIN, "Sustain:")
STR_SCHINESE (IDS_SETTING_PLAY_SUSTAIN, "延音：")

STR_ENGLISH  (IDS_SETTING_PLAY_PAGE1, "Page 1")
STR_SCHINESE (IDS_SETTING_PLAY_PAGE1, "第一页")

STR_ENGLISH  (IDS_SETTING_PLAY_PAGE2, "Page 2")
STR_SCHINESE (IDS_SETTING_PLAY_PAGE2, "第二页")

STR_ENGLISH  (IDS_SETTING_PLAY_PAGE3, "Page 3")
STR_SCHINESE (IDS_SETTING_PLAY_PAGE3, "第三页")

STR_ENGLISH  (IDS_SETTING_PLAY_PAGE4, "Page 4")
STR_SCHINESE (IDS_SETTING_PLAY_PAGE4, "第四页")

// audio setting page
STR_ENGLISH  (IDS_SETTING_LIST_AUDIO, "Audio")
STR_SCHINESE (IDS_SETTING_LIST_AUDIO, "音频")

STR_ENGLISH  (IDS_SETTING_AUDIO_OUTPUT, "Output")
STR_SCHINESE (IDS_SETTING_AUDIO_OUTPUT, "输出")

STR_ENGLISH  (IDS_SETTING_AUDIO_DEVICE, "Device:")
STR_SCHINESE (IDS_SETTING_AUDIO_DEVICE, "设备：")

STR_ENGLISH  (IDS_SETTING_AUDIO_AUTO, "Auto")
STR_SCHINESE (IDS_SETTING_AUDIO_AUTO, "自动选择")

STR_ENGLISH  (IDS_SETTING_AUDIO_BUFFER, "Buffer:")
STR_SCHINESE (IDS_SETTING_AUDIO_BUFFER, "延时：")

STR_ENGLISH  (IDS_SETTING_AUDIO_VOLUME, "Volume:")
STR_SCHINESE (IDS_SETTING_AUDIO_VOLUME, "音量：")

STR_ENGLISH  (IDS_SETTING_AUDIO_PLAYBACK, "Play")
STR_SCHINESE (IDS_SETTING_AUDIO_PLAYBACK, "播放")

STR_ENGLISH  (IDS_SETTING_AUDIO_PLAY_SPEED, "Speed:")
STR_SCHINESE (IDS_SETTING_AUDIO_PLAY_SPEED, "播放速度：")

// MIDI input setting page
STR_ENGLISH  (IDS_SETTING_LIST_MIDI, "MIDI In")
STR_SCHINESE (IDS_SETTING_LIST_MIDI, "MIDI输入")

// GUI setting page
STR_ENGLISH  (IDS_SETTING_LIST_GUI, "GUI")
STR_SCHINESE (IDS_SETTING_LIST_GUI, "界面")

STR_ENGLISH  (IDS_SETTING_GUI_RESIZE, "Allow scale window:")
STR_SCHINESE (IDS_SETTING_GUI_RESIZE, "允许缩放窗口：")

STR_ENGLISH  (IDS_SETTING_GUI_HOTKEY, "Disable all system hotkey:")
STR_SCHINESE (IDS_SETTING_GUI_HOTKEY, "屏蔽所有系统按键：")

STR_ENGLISH  (IDS_SETTING_GUI_TRANSPOSE, "MIDI Transpose:")
STR_SCHINESE (IDS_SETTING_GUI_TRANSPOSE, "MIDI键盘变调：")

STR_ENGLISH  (IDS_SETTING_GUI_SHOW_VSTI, "Show VSTi instruments:")
STR_SCHINESE (IDS_SETTING_GUI_SHOW_VSTI, "显示 VSTi 音源：")

STR_ENGLISH  (IDS_SETTING_GUI_SHOW_MIDI, "Show MIDI instruments:")
STR_SCHINESE (IDS_SETTING_GUI_SHOW_MIDI, "显示 MIDI 音源：")

STR_ENGLISH  (IDS_SETTING_GUI_ANIMATION, "Animation:")
STR_SCHINESE (IDS_SETTING_GUI_ANIMATION, "键盘动画速度：")

STR_ENGLISH  (IDS_SETTING_GUI_TRANSPARENCY, "Transparency:")
STR_SCHINESE (IDS_SETTING_GUI_TRANSPARENCY, "界面透明度：")

STR_ENGLISH  (IDS_SETTING_GUI_FIXED_DOH, "Note display:")
STR_SCHINESE (IDS_SETTING_GUI_FIXED_DOH, "音符显示：")

STR_ENGLISH  (IDS_SETTING_GUI_AUTO_COLOR, "Keyboard color:")
STR_SCHINESE (IDS_SETTING_GUI_AUTO_COLOR, "键盘颜色：")

STR_ENGLISH  (IDS_SETTING_GUI_AUTO_COLOR_CLASSIC, "Classic")
STR_SCHINESE (IDS_SETTING_GUI_AUTO_COLOR_CLASSIC, "经典")

STR_ENGLISH  (IDS_SETTING_GUI_AUTO_COLOR_CHANNEL, "Channel")
STR_SCHINESE (IDS_SETTING_GUI_AUTO_COLOR_CHANNEL, "通道")

STR_ENGLISH  (IDS_SETTING_GUI_AUTO_COLOR_VELOCITY, "Velocity")
STR_SCHINESE (IDS_SETTING_GUI_AUTO_COLOR_VELOCITY, "力度")

STR_ENGLISH  (IDS_SETTING_GUI_PREVIEW_COLOR, "Preview color:")
STR_SCHINESE (IDS_SETTING_GUI_PREVIEW_COLOR, "预览颜色：")

STR_ENGLISH  (IDS_SETTING_GUI_NOTE_DISPLAY, "Note display:")
STR_SCHINESE (IDS_SETTING_GUI_NOTE_DISPLAY, "音符显示：")

STR_ENGLISH  (IDS_SETTING_GUI_NOTE_DISPLAY_NAME,  "Name")
STR_SCHINESE (IDS_SETTING_GUI_NOTE_DISPLAY_NAME,  "音名")

STR_ENGLISH  (IDS_SETTING_GUI_NOTE_DISPLAY_DOH,  "DOH")
STR_SCHINESE (IDS_SETTING_GUI_NOTE_DISPLAY_DOH,  "唱名")

STR_ENGLISH  (IDS_SETTING_GUI_NOTE_DISPLAY_FIXED_DOH,  "Fixed-DOH")
STR_SCHINESE (IDS_SETTING_GUI_NOTE_DISPLAY_FIXED_DOH,  "固定唱名")

// keymap setting page
STR_ENGLISH  (IDS_SETTING_LIST_KEYMAP, "Keymap")
STR_SCHINESE (IDS_SETTING_LIST_KEYMAP, "键盘脚本")

STR_ENGLISH  (IDS_SETTING_KEYMAP_UPDATE, "Update")
STR_SCHINESE (IDS_SETTING_KEYMAP_UPDATE, "更新")

STR_ENGLISH  (IDS_SETTING_KEYMAP_APPLY, "Apply")
STR_SCHINESE (IDS_SETTING_KEYMAP_APPLY, "应用")


// About dialog
STR_ENGLISH  (IDS_ABOUT_CAPTION, "About FreePiano")
STR_SCHINESE (IDS_ABOUT_CAPTION, "关于 FreePiano")

STR_ENGLISH  (IDS_ABOUT_DESCRIPTION, "FreePiano is a free software.")
STR_SCHINESE (IDS_ABOUT_DESCRIPTION, "FreePiano 是一款免费软件，你可以随意使用、拷贝和发布。")

STR_ENGLISH  (IDS_ABOUT_VERSION, "Version:")
STR_SCHINESE (IDS_ABOUT_VERSION, "版本：")
STR_ENGLISH  (IDS_ABOUT_VERSION_VALUE, "1.8")
STR_SCHINESE (IDS_ABOUT_VERSION_VALUE, "1.8")

STR_ENGLISH  (IDS_ABOUT_AUTHOR, "Author:")
STR_SCHINESE (IDS_ABOUT_AUTHOR, "程序开发：")
STR_ENGLISH  (IDS_ABOUT_AUTHOR_VALUE, "Li Jia (tiwb@msn.com)")
STR_SCHINESE (IDS_ABOUT_AUTHOR_VALUE, "李佳 (tiwb@msn.com)")

STR_ENGLISH  (IDS_ABOUT_HOMEPAGE, "http://freepiano.tiwb.com")
STR_SCHINESE (IDS_ABOUT_HOMEPAGE, "http://freepiano.tiwb.com")

STR_ENGLISH  (IDS_ABOUT_THANKS, "Thanks to all that gives this software valuable advice.")
STR_SCHINESE (IDS_ABOUT_THANKS, "感谢所有键盘钢琴爱好者对本软件的支持及建议！")

// Song info dialog
STR_ENGLISH  (IDS_SONG_INFO_CAPTION, "Song infomation")
STR_SCHINESE (IDS_SONG_INFO_CAPTION, "歌曲信息")

STR_ENGLISH  (IDS_SONG_INFO_TITLE, "Title:")
STR_SCHINESE (IDS_SONG_INFO_TITLE, "标题：")

STR_ENGLISH  (IDS_SONG_INFO_AUTHOR, "Author:")
STR_SCHINESE (IDS_SONG_INFO_AUTHOR, "演奏者：")

STR_ENGLISH  (IDS_SONG_INFO_DESCRIPTION, "Description:")
STR_SCHINESE (IDS_SONG_INFO_DESCRIPTION, "说明：")

STR_ENGLISH  (IDS_SONG_INFO_COMPATIBITY, "(This song may incompatible with current version)")
STR_SCHINESE (IDS_SONG_INFO_COMPATIBITY, "（这首歌使用了一些之前版本的特性，可能与当前版本不兼容）")

STR_ENGLISH  (IDS_SONG_INFO_OK, "OK")
STR_SCHINESE (IDS_SONG_INFO_OK, "确定")

STR_ENGLISH  (IDS_SONG_INFO_CANCEL, "Cancel")
STR_SCHINESE (IDS_SONG_INFO_CANCEL, "取消")

// Exporting dialog
STR_ENGLISH  (IDS_EXPORTING_CAPTION, "Exporting...")
STR_SCHINESE (IDS_EXPORTING_CAPTION, "正在导出...")

STR_ENGLISH  (IDS_EXPORTING_CANCEL, "Cancel")
STR_SCHINESE (IDS_EXPORTING_CANCEL, "取消")

// Key setting dialog
STR_ENGLISH  (IDS_KEYSETTING_CAPTION,   "Key: %s")
STR_SCHINESE (IDS_KEYSETTING_CAPTION,   "按键： %s")

STR_ENGLISH  (IDS_KEYSETTING_NOTE,   "Note:")
STR_SCHINESE (IDS_KEYSETTING_NOTE,   "音符：")

STR_ENGLISH  (IDS_KEYSETTING_OCTAVE,   "Octave:")
STR_SCHINESE (IDS_KEYSETTING_OCTAVE,   "八度：")

STR_ENGLISH  (IDS_KEYSETTING_CHANNEL,   "Channel:")
STR_SCHINESE (IDS_KEYSETTING_CHANNEL,   "通道：")

STR_ENGLISH  (IDS_KEYSETTING_AUTOCLOSE, "Auto Close")
STR_SCHINESE (IDS_KEYSETTING_AUTOCLOSE, "自动关闭")

STR_ENGLISH  (IDS_KEYSETTING_AUTOAPPLY, "Auto Apply")
STR_SCHINESE (IDS_KEYSETTING_AUTOAPPLY, "自动应用")

STR_ENGLISH  (IDS_KEYSETTING_PRESET, "Preset...")
STR_SCHINESE (IDS_KEYSETTING_PRESET, "预设...")

STR_ENGLISH  (IDS_KEYSETTING_CLEAR, "Clear")
STR_SCHINESE (IDS_KEYSETTING_CLEAR, "清除")

STR_ENGLISH  (IDS_KEYSETTING_REFRESH, "Refresh")
STR_SCHINESE (IDS_KEYSETTING_REFRESH, "刷新")

STR_ENGLISH  (IDS_KEYSETTING_APPLY, "Apply")
STR_SCHINESE (IDS_KEYSETTING_APPLY, "应用")


// default labels
STR_ENGLISH  (IDS_KEY_LABEL_PLAY, "Play")
STR_SCHINESE (IDS_KEY_LABEL_PLAY, "播放")

STR_ENGLISH  (IDS_KEY_LABEL_RECORD, "Rec")
STR_SCHINESE (IDS_KEY_LABEL_RECORD, "录制")

STR_ENGLISH  (IDS_KEY_LABEL_STOP, "Stop")
STR_SCHINESE (IDS_KEY_LABEL_STOP, "停止")

STR_ENGLISH  (IDS_KEY_LABEL_KEYSIGNATURE, "KS")
STR_SCHINESE (IDS_KEY_LABEL_KEYSIGNATURE, "调")

STR_ENGLISH  (IDS_KEY_LABEL_TRANSPOSE, "TP")
STR_SCHINESE (IDS_KEY_LABEL_TRANSPOSE, "移")

STR_ENGLISH  (IDS_KEY_LABEL_OCTAVE, "OC")
STR_SCHINESE (IDS_KEY_LABEL_OCTAVE, "八")

STR_ENGLISH  (IDS_KEY_LABEL_VELOCITY, "V")
STR_SCHINESE (IDS_KEY_LABEL_VELOCITY, "力")

STR_ENGLISH  (IDS_KEY_LABEL_CHANNEL, "CH")
STR_SCHINESE (IDS_KEY_LABEL_CHANNEL, "通")

STR_ENGLISH  (IDS_KEY_LABEL_VOLUME, "VO")
STR_SCHINESE (IDS_KEY_LABEL_VOLUME, "音")

STR_ENGLISH  (IDS_KEY_LABEL_GROUP, "GP")
STR_SCHINESE (IDS_KEY_LABEL_GROUP, "组")

STR_ENGLISH  (IDS_KEY_LABEL_PROGRAM, "P")
STR_SCHINESE (IDS_KEY_LABEL_PROGRAM, "P")

STR_ENGLISH  (IDS_KEY_LABEL_NOTE_PRESSURE, "Np")
STR_SCHINESE (IDS_KEY_LABEL_NOTE_PRESSURE, "力度")

STR_ENGLISH  (IDS_KEY_LABEL_PRESSURE, "Cp")
STR_SCHINESE (IDS_KEY_LABEL_PRESSURE, "力度")

STR_ENGLISH  (IDS_KEY_LABEL_PITCH, "Pitch")
STR_SCHINESE (IDS_KEY_LABEL_PITCH, "弯音")

STR_ENGLISH  (IDS_KEY_LABEL_BANK, "BK")
STR_SCHINESE (IDS_KEY_LABEL_BANK, "BK")

STR_ENGLISH  (IDS_KEY_LABEL_SUSTAIN, "SU")
STR_SCHINESE (IDS_KEY_LABEL_SUSTAIN, "延")

STR_ENGLISH  (IDS_KEY_LABEL_MODULATION, "Mod")
STR_SCHINESE (IDS_KEY_LABEL_MODULATION, "颤音")

STR_ENGLISH  (IDS_KEY_LABEL_FOLLOW_KEY, "FK")
STR_SCHINESE (IDS_KEY_LABEL_FOLLOW_KEY, "跟随")

STR_ENGLISH  (IDS_NOTIFY_UPDATE_TITLE, "Update avaiable")
STR_SCHINESE (IDS_NOTIFY_UPDATE_TITLE, "更新提醒")

STR_ENGLISH  (IDS_NOTIFY_UPDATE, "FreePiao %s is avaiable now, would you like to check it out now?")
STR_SCHINESE (IDS_NOTIFY_UPDATE, "FreePiano %s 已经发布了， 要去看看吗？")

